SELECT fp.NAME AS PERS_NAME, pptids.KEYNAME AS pptive_keyname, ccids.KEYNAME AS CC_KEYNAME, eed.NAME AS ED, ecve.VERB  AS verbname
FROM  FD_PROFILE_TYPE fpt 
INNER JOIN CCADMIN_IDMAP IDS ON fpt.id = IDS.ID AND IDS.KEYSET ='PROFILE'
INNER JOIN FD_PROFILE_TYPE_PERSPECTIVE fptp ON fpt.ID  = fptp.PROFILE_ID 
INNER JOIN FD_PERSPECTIVE fp ON fp.ID = fptp.PERSPECTIVE_ID 
INNER JOIN CCADMIN_IDMAP pptids ON fp.ID = pptids.ID AND pptids.KEYSET = 'PPTIVE'
INNER JOIN EVA_CONTEXT_CONFIG ecc ON ecc.ID = fp.CONTEXT_CONFIG_ID 
INNER JOIN CCADMIN_IDMAP ccids ON ccids.ID  = ecc.ID  AND ccids.KEYSET ='CC'
INNER JOIN EVA_CONTEXT_VERB_ENTRY ecve ON ecve.CONFIG_ID = ecc.ID 
INNER JOIN EVA_ENTITY_DEFINITION eed ON eed.TYPE_ID =ecve.ENTITY_DEF_TYPE_ID 
WHERE fptp.PROFILE_ID = @PROFILE.{{profile_keyname | suggest(_keynames.PROFILE)}}
