--{"team_keyname":"ProServ"}

DELETE FROM CWQ_ENTITY__QUEUE WHERE ENTITY_ID = @TEAM.ProServ and ENTITY_TYPE_ID= @ET.Team;
DELETE FROM FD_HOMEPAGE_ASSIGNMENT WHERE ENTITY_ID=@TEAM.ProServ and ENTITY_TYPE_ID= @ET.Team;
DELETE FROM LOCALISED_FIELD WHERE OBJECT_TYPE='TeamED' and OBJECT_VERSION=@TEAM.ProServ;
DELETE FROM CE_TEAM WHERE ID = @TEAM.ProServ;
DELETE FROM LOCALISED_FIELD WHERE OBJECT_TYPE='QueueED' and OBJECT_VERSION=@QUEUE.ProServTeamQueue;
DELETE FROM CWQ_QUEUE where ID = @QUEUE.ProServTeamQueue;
DELETE FROM FRB_RULE_SET where ID = @RS.ProServTeamQueue;
