--["KnowledgeArticle","myTagset","","1","region","Y"]
INSERT INTO EVA_DYNAMIC_ENTITY_FIELD (ID, ENTITY_DEF_ID, NAME, INITIAL_VALUE, FIELD_TYPE_ID, FIELD_SEQUENCE, ENTITY_DEF_ENV_ID)
VALUES (@EDEF.KnowledgeArticleMyTagset, @ED.KnowledgeArticle, 'myTagset', '', @EFT.TagSetSelectionField, 1, @ENV.Dflt);

INSERT INTO LOCALISED_FIELD (OBJECT_TYPE,OBJECT_INSTANCE,OBJECT_VERSION,FIELD_NAME,LOCALE,LOOKUP_LOCALE,TEXT,IS_DELETED) VALUES ('DynamicEntityDefinitionED','KnowledgeArticleED',@ED.KnowledgeArticle,'fields.myTagset.displayName','en-GB','default','My Tagset','N');


INSERT INTO EVA_DYN_ENT_FIELD_PROPERTIES (ID, RELEASE_ID, FIELD_ID, ENTITY_DEF_TYPE_ID,ENTITY_DEF_TYPE_ENV_ID) 
VALUES (@EDEFP.KnowledgeArticleMyTagset, @RELEASE.ID, @EDEF.KnowledgeArticleMyTagset, @ET.TagSetFieldProperties,@ENV.Dflt);

INSERT INTO EVA_DYN_ENTITY_FIELD_TAGSET_PR (TENANT_ID, ID, RELEASE_ID, TAGSET_NAME, IS_MULTISELECT) VALUES (
'default',  -- TENANT_ID
@EDEFP.KnowledgeArticleMyTagset,  -- ID
@RELEASE.ID,  -- RELEASE_ID
'region',  -- TAGSET_NAME
'Y' -- IS_MULTISELECT
);

