--{"agent_keyname":"SYSTEMADMIN","queue_keyname":"DEFAULTQUEUE"}
INSERT INTO CWQ_ENTITY__QUEUE (TENANT_ID, ENTITY_ID, ENTITY_ENV_ID, ENTITY_TYPE_ID, ENTITY_TYPE_ENV_ID, QUEUE_ID, QUEUE_ENV_ID, RELEASE_ID) 
VALUES ('default',
	@PERSON.SYSTEMADMIN,
	@ENV.Dflt,
	@ET.Agent,
	@ENV.Dflt,
	@QUEUE.DEFAULTQUEUE,
	@ENV.Dflt,
	@RELEASE.ID);
