--{"profile_keyname":"BUSINESS_ADMIN","perspective_keyname":"SUPERVISORHOME","seq_no":"1"}
INSERT INTO FD_PROFILE_TYPE_PERSPECTIVE (PROFILE_ID,PROFILE_ENV_ID,PERSPECTIVE_ID,PERSPECTIVE_ENV_ID,SEQ_NO,RELEASE_ID,TENANT_ID,CONTEXT_UPDATER_DEFAULT) VALUES (
	@PROFILE.BUSINESS_ADMIN, --PROFILE_ID
	@ENV.Dflt, --PROFILE_ENV_ID
	@PPTIVE.SUPERVISORHOME, --PERSPECTIVE_ID
	@ENV.Dflt, --PERSPECTIVE_ENV_ID
	1, --SEQ_NO
	@RELEASE.ID, --RELEASE_ID
	'default', --TENANT_ID
	'N' --CONTEXT_UPDATER_DEFAULT
);

