--{"host_keyname":"MyPrivateHost","url_keyname":"MyPrivateURL"}
DELETE FROM EVA_ENTITY__TAGSET_SELECTION
WHERE ENTITY_ID = @WIU.MyPrivateURL;

DELETE FROM LOCALISED_FIELD
WHERE OBJECT_VERSION = @WIU.MyPrivateURL
and OBJECT_TYPE = 'WebIntegrationURLED';

DELETE FROM FWI_URL
WHERE ID = @WIU.MyPrivateURL;

DELETE FROM EVA_TAGSET_SELECTION
WHERE ID = @WIU.MyPrivateURL;

