--{"entity_id":"VerbAudit"}
DELETE FROM EVA_ENTITY_DEFINITION 
WHERE ID = @ED.VerbAudit;

DELETE FROM EVA_CATEGORY_ENTRY WHERE ENTITY_ID = @ED.VerbAudit; 

DELETE FROM LOCALISED_FIELD 
WHERE OBJECT_VERSION = @ED.VerbAudit
AND OBJECT_TYPE = 'EntityDefinitionED';

DELETE
FROM CCADMIN_IDMAP
WHERE KEYSET = 'ED'
AND ID =@ED.VerbAudit;
