--{"left_name":"TestAccount","right_name":"Contact","left_entity_keyname":"Customer","right_entity_keyname":"Contact"}
INSERT INTO EVA_ASSOCIATION_TYPE (ID,ENV_ID,OWNING_ENTITY_DEF_ID,OWNING_ENTITY_DEF_ENV_ID,LEFT_NAME,RIGHT_NAME,RIGHT_ENTITY_DEF_ID,RIGHT_ENTITY_DEF_ENV_ID,MIN_OCC,MAX_OCC,ASSOCIATION_INDEX,IS_DELETED,RELEASE_ID,CREATE_ED_VIEW_NAME,EDIT_ED_VIEW_NAME,OWNING_ENTITY_DEF_TYPE_ID,OWNING_ENTITY_DEF_TYPE_ENV_ID,RIGHT_ENTITY_DEF_TYPE_ID,RIGHT_ENTITY_DEF_TYPE_ENV_ID,TENANT_ID) 
VALUES (
	@EAT.TestAccountContact, --ID
	@ENV.Dflt, --ENV_ID
	@ED.Customer, -- OWNING_ENTITY_DEF_ID
	@ENV.Dflt, --OWNING_ENTITY_DEF_ENV_ID
	'TestAccount-Contact', --LEFT_NAME
	'Contact-TestAccount', --RIGHT_NAME
	@ED.Contact, --RIGHT_ENTITY_DEF_ID
	@ENV.Dflt, --RIGHT_ENTITY_DEF_ENV_ID
	1, --MIN_OCC
	1, --MAX_OCC
	1, --ASSOCIATION_INDEX
	'N', --IS_DELETED
	@RELEASE.ID, --RELEASE_ID
	null, --CREATE_ED_VIEW_NAME
	null, --EDIT_ED_VIEW_NAME
	2035, --OWNING_ENTITY_DEF_TYPE_ID
	@ENV.Dflt, --OWNING_ENTITY_DEF_TYPE_ENV_ID
	850, --RIGHT_ENTITY_DEF_TYPE_ID
	@ENV.Dflt, --RIGHT_ENTITY_DEF_TYPE_ENV_ID
	'default' --TENANT_ID
);
