SELECT ee.SYSTEM_NAME
FROM FD_PROFILE_TYPE fpt 
INNER JOIN EVA_ENTITY__ENTITLEMENT eee ON fpt.ID =eee.ENTITY_ID AND eee.ENTITY_TYPE_ID = @ET.ProfileType
INNER JOIN EVA_ENTITLEMENT ee ON eee.ENTITLEMENT_ID = ee.ID
WHERE fpt.ID =@PROFILE.{{profile_keyname | suggest(_keynames.PROFILE)}}
order by ee.SYSTEM_NAME
