
SELECT ci.KEYNAME  AS PDR_KEYNAME,epdr.CONFIG_ID ,EPDR.CONFIG_TYPE_ID,epd.REPOSITORY_PATH,epd."TYPE"  
FROM EVA_PROCESS_DESCRIPTOR epd
INNER JOIN EVA_PROCESS_DESC_REFERENCE epdr ON epdr.PROCESS_DESCRIPTOR_ID  = epd.id
INNER JOIN CCADMIN_IDMAP ci ON ci.KEYSET ='PDR' AND ci.id = epdr.ID 
WHERE epd.REPOSITORY_PATH  ='{{repository_path | codepath()}}'
