#ENTITY DEFINITION 
ed_by_keyname=SELECT ED.ID,ED.TYPE_ID,IDS.KEYNAME,ED.NAME,ED.LOGICAL_OBJ_PATH,ED.INTERFACE_PATH,ED.SUPER_ENTITY_DEFINITION FROM EVA_ENTITY_DEFINITION ED, CCADMIN_IDMAP IDS WHERE ED.ID = IDS.ID AND IDS.KEYNAME ='{}' AND IDS.KEYSET='ED'
ed_by_id=SELECT ED.ID,IDS.KEYNAME,ED.NAME,ED.LOGICAL_OBJ_PATH,ED.INTERFACE_PATH,ED.SUPER_ENTITY_DEFINITION FROM EVA_ENTITY_DEFINITION ED, CCADMIN_IDMAP IDS WHERE ED.ID = IDS.ID AND ED.ID ='{}' AND IDS.KEYSET='ED'
ed_by_keyname_n_locale=SELECT ED.ID, ED.NAME, ED.LOGICAL_OBJ_PATH, ED.INTERFACE_PATH, ED.SUPER_ENTITY_DEFINITION, ED.IS_BASIC, ED.SUPPORTS_READONLY, ED.IS_EXPANDABLE, LF1.TEXT AS DISPLAY_NAME, EC_IDS.KEYNAME AS CATEGORY_KEYNAME, LF2.TEXT AS DESCRIPTION FROM EVA_ENTITY_DEFINITION ed LEFT JOIN EVA_CATEGORY_ENTRY c on ed.id = c.entity_id INNER JOIN CCADMIN_IDMAP ed_ids on ED.ID = ed_IDS.ID INNER JOIN CCADMIN_IDMAP ec_ids on c.CATEGORY_ID = ec_IDS.ID INNER JOIN LOCALISED_FIELD LF1 ON ED.ID = LF1.OBJECT_VERSION INNER JOIN LOCALISED_FIELD LF2 ON ED.ID = LF2.OBJECT_VERSION where ED_IDS.KEYNAME ='{}'AND ED_IDS.KEYSET='ED' AND LF1.OBJECT_TYPE='EntityDefinitionED' AND LF1.LOCALE='en-US' AND LF1.FIELD_NAME ='displayName' AND LF2.OBJECT_VERSION = ED.ID AND LF2.OBJECT_TYPE='EntityDefinitionED' AND LF2.LOCALE='en-US' AND LF2.FIELD_NAME ='description' AND EC_IDS.KEYSET = 'EC' 

#CATEGORY
category_by_keyname=SELECT IDMAP.KEYNAME,C.SYSTEM_NAME FROM EVA_CATEGORY C, CCADMIN_IDMAP IDMAP WHERE IDMAP.ID = C.ID AND IDMAP.KEYSET ='EC' AND IDMAP.ID =@EC.{}

#VERB 
verbs_by_ed=SELECT V.NAME,IDMAP.KEYNAME FROM EVA_VERB V, CCADMIN_IDMAP IDMAP where V.ENTITY_DEF_ID = @ED.{} AND IDMAP.KEYSET='V' AND IDMAP.ID =V.ID;
v_names_by_ed=SELECT V.NAME FROM EVA_VERB V  where  V.ENTITY_DEF_ID = @ED.{}
v_names_by_et=SELECT V.NAME FROM EVA_VERB V, EVA_ENTITY_DEFINITION ED WHERE V.ENTITY_DEF_ID = ED.ID AND ED.TYPE_ID = @ET.{}

#PROCESS DESCRIPTOR REFERENCE
pdr_by_keyname=SELECT PDR.ID, IDMAP.KEYNAME as PD_KEYNAME FROM EVA_PROCESS_DESC_REFERENCE PDR, CCADMIN_IDMAP IDMAP  where PDR.PROCESS_DESCRIPTOR_ID = IDMAP.ID AND IDMAP.KEYSET='PD' AND PDR.id =@PDR.{};

#PROCESS DESCRIPTOR 
pd_by_ed_n_vname=SELECT PDR.ID, PD.NAME as PD_NAME,PD.CONFIG_PROCESS_ID,PD.TYPE as PD_TYPE,PDR.CONFIG_ID as PDR_CONFIG_ID, PDR.CONFIG_TYPE_ID as PDR_CONFIG_TYPE_ID, PD.REPOSITORY_PATH  FROM EVA_VERB V INNER JOIN EVA_PROCESS_DESC_REFERENCE PDR ON V.PROCESS_DESC_REF_ID =PDR.ID INNER JOIN EVA_PROCESS_DESCRIPTOR PD ON PDR.PROCESS_DESCRIPTOR_ID =PD.ID INNER JOIN CCADMIN_IDMAP IDMAP ON IDMAP.ID =V.ENTITY_DEF_ID LEFT JOIN CCADMIN_IDMAP ID_ET ON PDR.CONFIG_TYPE_ID =ID_ET.ID and IDMAP.keyset='ET' WHERE  IDMAP.KEYSET ='ED' AND IDMAP.KEYNAME = '{}' AND V.NAME ='{}';
pd__by_ed_n_vnames=SELECT *  FROM EVA_VERB V, EVA_PROCESS_DESCRIPTOR PD, EVA_PROCESS_DESC_REFERENCE PDR, CCADMIN_IDMAP IDMAP WHERE V.PROCESS_DESC_REF_ID = PDR.ID AND PDR.PROCESS_DESCRIPTOR_ID = PD.ID AND IDMAP.ID = V.ENTITY_DEF_ID AND IDMAP.KEYSET ='ED' AND IDMAP.KEYNAME = '{}' AND V.NAME ='{}'
pd_by_repo_path=select PDR.ID AS PROCESS_DESC_REF_ID, PD.REPOSITORY_PATH from EVA_PROCESS_DESCRIPTOR PD, EVA_PROCESS_DESC_REFERENCE PDR where PDR.PROCESS_DESCRIPTOR_ID = PD.ID AND PD.REPOSITORY_PATH ='{}'
#AUX VERBS 
av_topseq_by_pers_keyname=SELECT SEQUENCE_NUM FROM FD_ENTITY__AUX_VERBS AV, CCADMIN_IDMAP IDMAP WHERE IDMAP.KEYNAME ='{}' AND IDMAP.KEYSET = 'PPTIVE' AND ENTITY_ID = IDMAP.ID ORDER BY SEQUENCE_NUM DESC

#PERSPECTIVE
v_by_pers_keyname=SELECT l.text as DISPLAY_NAME, cv.SEQUENCE_NUMBER, et_ids.keyname as ET_KEYNAME, CV.VERB FROM EVA_CONTEXT_VERB_ENTRY cv, EVA_ENTITY_DEFINITION ed, eva_verb v, LOCALISED_FIELD l, CCADMIN_IDMAP	et_ids where cv.ENTITY_def_type_id =ed.type_id and v.entity_def_id =ed.id and v.name =cv.verb and l.object_version = v.id and l.object_type='VerbED' and cv.config_id =@CC.{} and l.locale ='en-US' and l.field_name ='displayName' and l.is_deleted ='N' and et_ids.id = cv.ENTITY_DEF_TYPE_ID and et_ids.keyset='ET' order by cv.SEQUENCE_NUMBER, DISPLAY_NAME
perspectives_by_profile=SELECT * FROM FD_PROFILE_TYPE_PERSPECTIVE WHERE PROFILE_ID=@PROFILE.{} order by SEQ_NO desc
#AGENT
all_agents=SELECT * FROM AGENT

#USERS
all_users=SELECT ID, USERNAME FROM FU_USER

#ENTITLEMENTS
all_entitlements=SELECT idmap.ID, idmap.KEYNAME,SYSTEM_NAME FROM EVA_ENTITLEMENT e, CCADMIN_IDMAP idmap where e.id =idmap.id and idmap.keyset ='ENTLMNT'

#CCADMIN_VERSION
all_releases=SELECT * FROM CCADMIN_VERSION

#WORK_AREAS
all_work_areas=SELECT * FROM FD_WORK_AREA

#DYNAMIC_VIEW_TYPES
all_dynamic_view_types=SELECT cc.ID,cc.keyname FROM EVA_DYNAMIC_ENTITY_VIEW_TYPE vt, CCADMIN_IDMAP cc where vt.ENTITY_DEFINITION_TYPE_ID = cc.ID and cc.keyset='ET'
views_by_ed=SELECT CC.keyname, V.NAME FROM EVA_DYNAMIC_ENTITY_VIEW v, CCADMIN_IDMAP cc where v.ID = cc.id and cc.keyset = 'DEV' and v.ENTITY_DEF_ID =@ED.{}

#DYNAMIC_VIEW_FIELDS
fields_by_ed=SELECT f.NAME, cc.KEYNAME FROM EVA_DYNAMIC_ENTITY_FIELD f, CCADMIN_IDMAP cc where f.id = cc.id and cc.keyset= 'EDEF' and ENTITY_DEF_ID = @ED.{}
all_property_types=SELECT cc.KEYNAME FROM eva_entity_definition  ed, CCADMIN_IDMAP cc where cc.id =ed.TYPE_ID and name like '%Properties%' 
all_field_pds=SELECT pd.REPOSITORY_PATH, cc.keyname FROM EVA_PROCESS_DESCRIPTOR pd, CCADMIN_IDMAP cc where  pd.id = cc.id and cc.keyset='PD'
and TYPE =@PDT.Field
view_fields_by_view=SELECT VIEW_FIELD_SEQUENCE FROM EVA_DYNAMIC_ENTITY_VIEW_FIELD where DYN_ENTITY_VIEW_ID=@DEV.{}
view_groups=SELECT cc.*,g.GROUP_NAME FROM CCADMIN_IDMAP cc, EVA_DYNAMIC_ENTITY_VIEW_GROUP g where g.id = cc.id and keyset ='EDEVG' and view_id = @DEV.{};

#TAGS
tags_by_parent_keyname=SELECT name FROM eva_tag where parent_tag =@TAG.{} and is_deleted ='N' and is_retired ='N';

# DYNAMIC VERB LIST
edvl_by_type_id=SELECT idmap.keyname as edvl_keyname, idmap2.keyname || edvl.VERB_NAME as entity_Verb FROM CCADMIN_IDMAP IDMAP, CCADMIN_IDMAP IDMAP2, EVA_DYNAMIC_VERB_LIST EDVL WHERE idmap.KEYSET ='EDVL' AND  EDVL.ID = IDMAP.ID and IDMAP2.id = edvl.ENTITY_TYPE_ID and idmap2.keyset ='ET' AND edvl.TYPE_ID=@EDVLT.{};

#BACKGROUND_VERBS
bv_keynames_by_profile=SELECT entity_id, idmap.keyname  as BV_KEYNAME, BACKGROUND_VERB_ID FROM FA_ENTITY__BACKGROUND_VERB ebv, CCADMIN_IDMAP idmap where idmap.id = BACKGROUND_VERB_ID and idmap.KEYSET ='BV' and ENTITY_TYPE_ID = @ET.ProfileType and ENTITY_ID = @PROFILE.{};

#LOCALISED_FIELD
lf_object_types=SELECT OBJECT_TYPE FROM LOCALISED_FIELD GROUP BY OBJECT_TYPE ORDER BY OBJECT_TYPE;
lf_object_instances_by_ot=SELECT OBJECT_TYPE,OBJECT_INSTANCE  FROM LOCALISED_FIELD GROUP BY OBJECT_TYPE,OBJECT_INSTANCE HAVING OBJECT_TYPE='{}'; 
lf_field_names_by_ot_and_oi=SELECT OBJECT_TYPE,OBJECT_INSTANCE,FIELD_NAME  FROM LOCALISED_FIELD GROUP BY OBJECT_TYPE,OBJECT_INSTANCE,FIELD_NAME HAVING OBJECT_TYPE='{}' AND OBJECT_INSTANCE='{}';

#DB METADATA
table_metadata=SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH FROM USER_TAB_COLUMNS WHERE TABLE_NAME = '{}';
