INSERT INTO EVA_INTERCHANGEABLE_TYPE (ID,IS_ENTITY_DEFINITION,SYSTEM_NAME,NAME,DESCRIPTION,RELEASABLE,RELEASE_ID,SAVE_ORDER,JSON_MIGRATION_DOMAIN,JSON_MIGRATION_ORDER,IS_REMOTE,TENANT_ID) 
VALUES (
@EIT.TagObjects, --ID
'Y', --IS_ENTITY_DEFITION
'TagED', --SYSTEM_NAME
'Tag', --NAME
'Tag Objects', --Description
'Y',--RELEASEABLE
1,
null,
'Tagsets',
1,
'N',
'default');
INSERT INTO EVA_INTERCHANGEABLE_TYPE (ID,IS_ENTITY_DEFINITION,SYSTEM_NAME,NAME,DESCRIPTION,RELEASABLE,RELEASE_ID,SAVE_ORDER,JSON_MIGRATION_DOMAIN,JSON_MIGRATION_ORDER,IS_REMOTE,TENANT_ID) 
VALUES (@EIT.TagSetObjects, --ID
	'Y', --IS_ENTITY_DEFINITION
	'TagSetED',
	'Tag Set',
	'Tag Set Objects',
	'Y',
	1,
	null,
	'Tagsets',
	1,
	'N',
	'default');
