INSERT INTO FA_ENTITY__BACKGROUND_VERB (ENTITY_ID,ENTITY_ENV_ID,ENTITY_TYPE_ID,ENTITY_TYPE_ENV_ID,BACKGROUND_VERB_ID,RELEASE_ID,TENANT_ID)
VALUES (
	@PROFILE.{{profile_keyname | suggest(_keynames.PROFILE)}}, --ENTITY_ID
	@ENV.Dflt,--ENTITY_ENV_ID
	@ET.ProfileType, --ENTITY_TYPE_ID
	@ENV.Dflt, --ENTITY_TYPE_ID
	@BV.{{background_verb_keyname | suggest(_keynames.BV)}}, --BACKGROUND_VERB_ID
	@RELEASE.ID, --RELEASE_ID
	'default'--TENANT_ID
);
