--within the _KM_CONFIG schema...
INSERT INTO search_configuration (ITEM_TYPE,ITEM_SUBTYPE,ITEM_NAME,ITEM_VALUE,ITEM_VERSION,CREATED_DATE,UPDATED_DATE,TENANT_ID)
VALUES('ContentFormat','none',
	'{{dynamic_entity_name | description("dynamic_entity_name (e.g KnowledgeArticleED)")}}',
	'{"name":"{{dynamic_entity_name}}","description":"{{dynamic_entity_name}} content format","contentType":"{{dynamic_entity_name}}","mapping":[{"contentField":"id","indexField":"id","shared":[]},{"contentField":"originalId","indexField":"original_id","shared":[]},{"contentField":"weighting","indexField":"weighting","shared":[]},{"contentField":"contentType","indexField":"content_type","shared":[]},{"contentField":"publishedId","indexField":"published_id","shared":[]},{"contentField":"description","indexField":"description","shared":["Contact Center","Self Service"]},{"contentField":"locale","indexField":"locale","shared":[]},{"contentField":"language","indexField":"language","shared":[]},{"contentField":"entitlementList","indexField":"entitlements","shared":[]},{"contentField":"lastModifiedDate","indexField":"last_modified_date","shared":[]},{"contentField":"isFeatured","indexField":"featured","shared":[]},{"contentField":"tagList","indexField":"tags","shared":[]},{"contentField":"topic","indexField":"tags","shared":[]},{"contentField":"region","indexField":"tags","shared":[]},{"contentField":"product","indexField":"tags","shared":[]},{"contentField":"tagpaths","indexField":"tagpaths","shared":[]},{"contentField":"tagsets","indexField":"tagsets","shared":[]},{"contentField":"status","indexField":"workflow_state","shared":[]},{"contentField":"publishedDate","indexField":"published_date","shared":[]},{"contentField":"expiredDate","indexField":"expired_date","shared":[]},{"contentField":"ownerId","indexField":"owner_id","shared":[]},{"contentField":"lastModifiedById","indexField":"last_modified_by_id","shared":[]},{"contentField":"title","indexField":"title","shared":[]},{"contentField":"publicBody","indexField":"public_body","shared":["Contact Center","Self Service"]},{"contentField":"privateBody","indexField":"private_body","shared":["Contact Center"]},{"contentField":"contentCategory","indexField":"content_category","shared":[]},{"contentField":"averageRating","indexField":"average_rating","shared":[]},{"contentField":"numberOfRatings","indexField":"rating_count","shared":[]},{"contentField":"viewCount","indexField":"view_count","shared":[]},{"contentField":"publicSectionContent","indexField":"public_section","shared":[]},{"contentField":"privateSectionContent","indexField":"private_section","shared":[]},{"contentField":"publicSegmentContent","indexField":"public_section","shared":[]},{"contentField":"privateSegmentContent","indexField":"private_section","shared":[]},{"contentField":"knowledgeBase","indexField":"tags","shared":[]}]}',
	1,
	to_date('2019/06/07', 'yyyy/mm/dd'),
	to_date('2019/06/07', 'yyyy/mm/dd'),
	'default');
