--creates an agent with the same password as 'admin' user
INSERT INTO FU_USER (ID, USERNAME, LOCALE_ID, LOCALE_ENV_ID, IS_DELETED, VIRTUAL_ENVIRONMENT_ID, VIRTUAL_ENVIRONMENT_ENV_ID, TENANT_ID, CONTENT_LOCALE) VALUES (@USER.{{username}}, '{{username}}', @LOC.en_US, @ENV.Dflt, 'N', 1, @ENV.Dflt, 'default', '{{_locale}}');

{% include 'add_profile_to_agent.sql' %}

INSERT INTO CE_PERSON (ID, FIRST_NAME, FIRST_NAME_UPPER, LAST_NAME, LAST_NAME_UPPER, GENDER_ID, GENDER_ENV_ID, TITLE_ID, TITLE_ENV_ID, IS_DELETED, TENANT_ID, DO_NOT_DELETE) VALUES (@PERSON.{{username}}, '{{name}}', '{{name | upper()}}', '{{surname}}', '{{surname | upper()}}', 0, @ENV.Dflt, 0, @ENV.Dflt, 'N', 'default', 'N');

INSERT INTO CE_AGENT (ID, USER_ID, TENANT_ID, ORG_REALM_ID) VALUES (@PERSON.{{username}}, @USER.{{username}}, 'default', 'organisat');

INSERT INTO AGENT (USERNAME,PASSWORD,FULLNAME,EXPIRES,PERSON_ID,CONNECTON,DISABLED,GRACE,CREATED,ALLOWCONCURRENT,CONSISTENTIPONLY,LOGINFAILURES,LASTLOGGEDIN,SALT,ENCRYPTION_CLASSNAME,EXTERNALLY_AUTHENTICATED,TENANT_ID) 
VALUES ('{{username}}',--USERNAME
	'894ba6c900618739b47ed35f2a2ed87c5211c707042f17a90a1f7eaa2127623f',--PASSWORD
	'{{name}} {{surname}}',--FULLNAME
	TO_DATE('12/15/2099', 'MM/DD/YYYY'),--EXPIRES
	@USER.{{username}},--PERSON_ID
	1,--CONNECTON
	'no',--DISABLED
	0,--GRACE
	CURRENT_DATE,--CREATED
	1,--ALLOWCONCURRENT
	'no',--CONSISTENTIPONLY
	0,--LOGINFAILURES
	CURRENT_DATE,--LASTLOGGEDIN
	'L1+QSNiB48A=',--SALT
	'com.gtnet.common.security.algorithms.SHA256',--ENCRYPTION_CLASSNAME
	'no',--EXTERNALLY_AUTHENTICATED
	'default'--TENANT_ID
);

