
INSERT INTO EVA_DYNAMIC_VERB_PARAMETER (DYNAMIC_VERB_LIST_ID,DYNAMIC_VERB_LIST_ENV_ID,DYNAMIC_VERB_LIST_RELEASE_ID,PARAMETER_SOURCE_NAME,PARAMETER_DESTINATION_NAME,IS_MANDATORY,TENANT_ID)
VALUES (
	@EDVL.{{edvl_id}},--DYNAMIC_VERB_LIST_ID
	@ENV.Dflt, --DYNAMIC_VERB_LIST_ENV_ID
	@RELEASE.ID, --DYNAMIC_VERB_LIST_RELEASE_ID
	'{{parameter_source_name}}', --PARAMETER_SOURCE_NAME
	'{{parameter_destination_name}}',--PARAMETER_DESTINATION_NAME
	'{{parameter_is_mandatory}}',--IS_MANDATORY
	'default'--TENANT_ID
);
