--{"verb_name":"view"}
INSERT INTO EVA_DYNAMIC_VERB_LIST (ID,ENV_ID,RELEASE_ID,TYPE_ID,TYPE_ENV_ID,ENTITY_TYPE_ID,ENTITY_TYPE_ENV_ID,VERB_NAME,SEQUENCE_NO,TENANT_ID)
VALUES (@EDVL.ContactView, --ID
		@ENV.Dflt, --ENV_ID
		@RELEASE.ID, --RELEASE_ID
		@EDVLT.InlineViewContactConfig, -- TYPE_ID
		@ENV.Dflt, --TYPE_ENV_ID
		@ET.Contact, --ENTITY_TYPE_ID
		@ENV.Dflt,--ENTITY_TYPE_ENV_ID
		'view',--VERB_NAME
		@RELEASE.ID,--RELEASE_ID
		'default'--TENANT_ID
		);

INSERT INTO EVA_DYNAMIC_VERB_PARAMETER (DYNAMIC_VERB_LIST_ID,DYNAMIC_VERB_LIST_ENV_ID,DYNAMIC_VERB_LIST_RELEASE_ID,PARAMETER_SOURCE_NAME,PARAMETER_DESTINATION_NAME,IS_MANDATORY,TENANT_ID)
VALUES (
	@EDVL.ContactView,--DYNAMIC_VERB_LIST_ID
	@ENV.Dflt, --DYNAMIC_VERB_LIST_ENV_ID
	@RELEASE.ID, --DYNAMIC_VERB_LIST_RELEASE_ID
	'contact', --PARAMETER_SOURCE_NAME
	'contact',--PARAMETER_DESTINATION_NAME
	'Y',--IS_MANDATORY
	'default'--TENANT_ID
);
